version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.8

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - patchup-{{ .Environment.CACHE_VERSION }}-dependencies-{{ checksum "requirements/dev.txt" }}

      - run:
          name: install system dependencies
          # libsasl2-dev is required to install superset successfully
          command: |
            sudo apt-get update && sudo apt-get install libsasl2-dev

      - run:
          name: install dependencies
          command: |
            python -V
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip tox
            pip install -r requirements/dev.txt

      - save_cache:
          paths:
            - ./venv
          key: patchup-{{ .Environment.CACHE_VERSION }}-dependencies-{{ checksum "requirements/dev.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox

      - store_artifacts:
          path: test-reports
          destination: test-reports
